---
title: "Mulivariate Viz"
---

Use this file for practice with the **mulivariate viz** in-class activity.  Refer to the class website for details.
```{r}
library(ggplot2)
```

```{r}
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)
```
```{r}
#| fig-height: 5
#| fig-width: 4
ggplot(education, aes(x=sat, y=State)) +
  geom_boxplot() 
```
```{r}
#the range of the sat scores goes from just below 850 to just above 1100, it is pretty spread out and follows no pattern whatsoever, the explanation behind this might be just alphabetical ordering of the states without ordering them using specific characteristics.
```

```{r}
#Exercise 2a
ggplot(education, aes(x=expend, y=sat)) +
  geom_point() +
    geom_smooth(method = "lm")
```
```{r}
# Construct a plot of sat vs salary
# Include a "best fit linear regression model" (HINT: method = "lm")

ggplot(education, aes(x=salary, y=sat)) +
  geom_point() +
  geom_smooth(method = "lm")
```
```{r}
#Part b. 
#Spending is indirectly correlated with spending ie states with low spending also have higher sat scores.
```

```{r}
#Exercise 3: SAT Scores vs Per Pupil Spending and Teacher Salaries
#Construct one visualization of the relationship of sat with salary and expend. HINT: Start with just 2 variables and tweak that code to add the third variable. Try out a few things!
ggplot(education, aes(x=salary, y=sat, alpha = expend)) +
  geom_point() +
  geom_smooth(method = "lm")
```
```{r}

#(Exercise 4: Another way to Incorporate Scale
#It can be tough to distinguish color scales and size scales for quantitative variables. Another option is to discretize a quantitative variable, or basically cut it up into categories.

#Construct the plot below. Check out the code and think about what’s happening here. What happens if you change “2” to “3”?

#ggplot(education, aes(y = sat, x = salary, color = cut(expend, 2))) + 
#  geom_point() + 
 # geom_smooth(se = FALSE, method = "lm")

#Describe the trivariate relationship between sat, salary, and expend.)

ggplot(education, aes(y = sat, x = salary, color = cut(expend, 2))) + 
 geom_point() + 
  geom_smooth(se = FALSE, method = "lm")
```
```{r}
# Changing 2 to 3 changes the range, ie min and max and how many categories the data set is cut into. Sat is high in states where the salary is low, but it is also very highly correlated (lower) in states the expenditure is extremely low
```

```{r}
#Exercise 5: Finally an Explanation
#It’s strange that SAT scores seem to decrease with spending. But we’re leaving out an important variable from our analysis: the fraction of a state’s students that actually take the SAT. The fracCat variable indicates this fraction: low (under 15% take the SAT), medium (15-45% take the SAT), and high (at least 45% take the SAT).



#Part a
#Build a univariate viz of fracCat to better understand how many states fall into each category.



#Part b
#Build 2 bivariate visualizations that demonstrate the relationship between sat and fracCat. What story does your graphic tell and why does this make contextual sense?

#Part c
#Make a trivariate visualization that demonstrates the relationship of sat with expend AND fracCat. Highlight the differences in fracCat groups through color AND unique trend lines. What story does your graphic tell?
#Does it still seem that SAT scores decrease as spending increases?

#Part d
#Putting all of this together, explain this example of Simpson’s Paradox. That is, why did it appear that SAT scores decrease as spending increases even though the opposite is true?
```







