---
title: "Bivariate Viz"
---

Use this file for practice with the **bivariate viz** in-class activity.  Refer to the class website for details.

```{r}
library(ggplot2)
```

```{r}
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")
```

```{r}
head(elections)
```
```{r}
#Exercise 0
# **A**. 
ggplot(elections, aes(x=winner_20)) +
       geom_bar()
```
```{r}
#**B**
ggplot(elections, aes(x=repub_pct_20)) +
geom_histogram(color="white") 
```
```{r}
#Exercise 1
ggplot(elections, aes(y=repub_pct_20, x=repub_pct_16)) +
  geom_point()
```

```{r}
#**Exercise 2**
# Set up the plotting frame
# there are two variables which are now quantitative instead of categorical
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16))
```
```{r}
# Add a layer of points for each county
# Take note of the geom!
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point()
```
```{r}
# Change the shape of the points
# just changes the appearance of the shapes we see, makes it more or less clear
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
geom_point(shape = 10)
```

```{r}
# YOU TRY: Modify the code to make the points "orange"
# NOTE: Try to anticipate if "color" or "fill" will be useful here. Then try both.
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point(color="red", shape = 5)
```
```{r}
# Add a layer that represents each county by the state it's in
# Take note of the geom and the info it needs to run!
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_text(aes(label = state_abbr))
```
```{r}
# the relationship between republican support in 2020 and 2016 is positive, this can be seen with the upwards sloping curve, which is also supported by the line of best fit which is positive sloping as well. southern states eg Texas, Utah tend to deviate as these were more positively correlated and caused a positive result for 2020 from 2016
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point(color="red", shape = 5) +
geom_abline() +
   geom_text(aes(label = state_abbr))

```




