---
title: "Wrangling Viz"
---
```{r}
# Load tidyverse & data
library(tidyverse)
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")


```
exercise 1 
```{r}
elections_small <- elections |> 
  select(state_name, county_name, total_votes_20, repub_pct_20, dem_pct_20, total_votes_16, dem_pct_16)
```

```{r}
head(elections_small)
```

```{r}
head(elections)
```
exercise 2

```{r}
#Keep only data on counties in Hawaii
 elections_small |>
 filter(state_name == "Hawaii")
```
```{r}
# This makes it possible for us to filter two variables at once
 elections_small |> 
  filter(state_name %in% c("Hawaii", "Delaware"))
```
```{r}
# The important variable here is the repub_pct 20 percentage
elections_small |>
 filter(repub_pct_20 > "93.97")
```
```{r}
# The important variable here is the repub_pct 20 percentage
elections_small |>
 filter(repub_pct_20 >= 93.97)
```
 Keep only data on counties in Texas where the Democrat got more than 65% of the vote in 2020
# Do this 2 ways.
# Method 1: 2 filters with 1 condition each
#elections_small |> 
#  filter(___) |> 
#  filter(___)

# Method 2: 1 filter with 2 conditions
#elections_small |> 
#  filter(___, ___)

```{r}
#Method 1
elections_small |>
  filter(state_name == "Texas") |>
 filter(dem_pct_20 > 65)
```
```{r}
#Method 2
elections_small |> 
 filter(state_name== "Texas", dem_pct_20 > 65)
```

Exercise 3

Arrange the counties in elections_small from lowest to highest percentage of 2020 Republican support

```{r}
# Arrange the counties in elections_small from lowest to highest percentage of 2020 Republican support
# Print out just the first 6 rows
# elections_small |> 
#   arrange(___) |> 
#   head()

elections_small |> 
  arrange(county_name) |>
  arrange(desc(repub_pct_20)) |>
 head(6)

```












